version: '3.1'
services:
  #mongo:
  #  image: mongo
  #  networks:
  #    - backend
  #  restart: always
  #  container_name: mongo
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example
  #  ports:
  #    - 27017:27017
  #  volumes:
  #    - ./mongodb:/data/db
  
  #postgres:
  #  image: postgres
  #  networks:
  #    - backend
  #  restart: always
  #  container_name: postgres
  #  environment:
  #    POSTGRES_PASSWORD: example
  #    PGDATA: /var/lib/postgresql/data/pgdata
  #  ports:
  #    - 5432:5432
  #  volumes:
  #    - ./postgres:/var/lib/postgresql/data
  
  #rabbitmq:
  #  image: rabbitmq:management
  #  networks:
  #    - backend
  #  restart: always
  #  container_name: rabbitmq
  #  ports:
  #    - 5672:5672
  #    - 15672:15672
  
  #redis:
  #  image: bitnami/redis:latest
  #  networks:
  #    - backend
  #  restart: always
  #  container_name: redis
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  ports:
  #    - 6379:6379
  #  volumes:
  #    - ./redis:/bitnami/redis/data

  #redis-insight:
  #  image: redislabs/redisinsight:latest
  #  networks:
  #    - backend
  #  restart: always
  #  container_name: redis-insight
  #  ports:
  #    - 8001:8001
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    networks:
      - backend
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    networks:
      - backend
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
    volumes:
      - ./kibana:/usr/share/kibana/config

      
  etcd:
    image: bitnami/etcd:3
    restart: always
    networks:
      - backend
    container_name: etcd3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
       - ./etcd:/default.etcd


networks:
  backend:
    driver: bridge
